### ISSUE TITLE
CMake comments

### ISSUE THREAD

**Issue by mathius** [crocs-muni/EACirc#105]
- What is "install prefix" good for in our case? I'm slightly worried by filling in "C:/Program Files/EACirc", which is the default.
- MSVC filters for directories are a bit strange, they do not support multi-level structure and ignore "Source files/Header files" filters.
- Short annotations for non-intuitive build targets for the wiki? INSTALL, RUN_TESTS, ZERO_CHECK
- Ctest still fails (debug on Win64, msvc12)
- commit version not automatically updated on Windows using MS Visual Studio

**Comment by mathius** [comment]
- install target removed
- VS now has hierarchical directories
- non-intuitive targets removed

- commit versions not updating on linux either

**Comment by mathius** [comment]
- Running CTest hides EACirc output (log) during tests. This way, if an automatic test fails, I know neither which test it was nor what happened.

**Comment by mathius** [comment]
Fixed commit version updating during build process. Tested on Linux, Win should be ok.

**Comment by mathius** [comment]
* Make CMake copy required sample scripts next to OneClick linked binary.

**Comment by mathius** [comment]
* Add a 32bit target? Currently, compiling 32-bit in Visual Studio is rather painful :-/ (but Metacentrum machines require it).

**Comment by mathius** [comment]
* Regarding target dependency graph in documentation: Estream depends on galib and sha3 and caesar don't? How come?

**Comment by mathius** [comment]
* Cleaning target should delete result files (log, txt, xml, ...) as well.

**Comment by mathius** [comment]
* Unify build/install process -- oneclick binary is copied on install, eacirc on build, oneclick should copy also sample sicripts (and configs?), probably deployed into separate folder (as it generated multiple files).
* Unify cleaning process -- oneclick binary not removed, eacirc so, generated results not removed. What about oneclick data?

-> Both above items are for further discussion. What about default not building oneclick (and building it separately into the same "run" folder)?

**Comment by LuboO** [comment]
-> script_samples folder (with scripts inside) have to be in same folder as oneclick binary, otherwise application will fail. Script samples are not needed for running, but could be copied for convenience. Oneclick binary generates main log and either results or scripts and folder with generated configs into folder the binary is in. I guess it would be better if the binary was in separate folder.

-> What exactly do you mean by oneclick data? Logs (main and batch ones) can be deleted, generated results shouldn't be and deleting configs/scripts could have quite negative impact (generated upload/download scripts are paired and if someone deletes his download script before downloading results he would have to create new one and that can be tricky)

**Comment by mathius** [comment]
oneclick data = exactly what you write (logs, generated scripts, ...)
Intuitively, I would want the clean process to remove the logs, circuits, etc. for EACirc. But oneclick, I cannot do so (generated scripts and such, as you write). Ideally, the solution should be consistent (either remove everything or nothing). That's why there was the last comment that these things are for further discussion.

**Comment by xtracko** [comment]
> Running CTest hides EACirc output (log) during tests. This way, if an automatic test fails, I know neither which test it was nor what happened.

Solved by adding custom target named check. I also updated .travis.yml. I am afraid I cant do more with cmake.

> Add a 32bit target? Currently, compiling 32-bit in Visual Studio is rather painful :-/ (but Metacentrum machines require it).

I do not understand the request. Does not the CMake provide a predefined generator for 32 bit msvc build?

**Comment by xtracko** [comment]
Documentation was updated.

**Comment by mathius** [comment]
> > Running CTest hides EACirc output (log) during tests. This way, if an automatic test fails, I know neither which test it was nor what happened.

> Solved by adding custom target named check. I also updated .travis.yml. I am afraid I cant do more with cmake.

Output is produced only in case of failure, it should produced in all cases, since passing tests lasting more than 10 minutes cause Travis to think the build is broken.
https://travis-ci.org/crocs-muni/EACirc/builds/72474846
Other option is to search TravisCI documentation for possible workaround.

**Comment by mathius** [comment]
There is a workaround, but it would be better to have test outputs (we would not be limited by those 20 minutes either).
http://docs.travis-ci.com/user/build-timeouts/

**Comment by mathius** [comment]
Hm, Travis used to run tests in 4 minutes and now time-outs in 13. My PC runs the tests successfully (both via CLI and 'check' target) in under 5 minutes as well.

**Comment by xtracko** [comment]
I threw away ctest and returned to the old ways in @bb81fd7 so the output of eacirc is always visible.

I dint noticed the default timeout on travis. Almost all my jobs run under 10 minutes.
