### ISSUE TITLE
OneClick comments

### ISSUE THREAD

**Issue by mathius** [crocs-muni/EACirc#106]
- oneclick should probably end with error (or at least warning), if no config was generated
- binary depends on sample scripts, but current build system compiles the binary elsewhere
=> either explicitly state what files are necessary for running or load these into the binary in compile time
- sample clean config issues an error (as a sample it should be directly usable)
- oneclick should check the WUidentifier for me (if it exceed 63 chars, error should be raised)
- specifying log WUidentifier results in error in opening the output file (upload script)

**Comment by LuboO** [comment]
Commit 3c395b9a6fc3388d451d5d5b2041a97cb68442dc

-> ends with error now, no scripts neither directories are generated
-> stated in wiki under Running Oneclick/Necessary files. Idea of script samples is that user don't have to recompile application after sample change, loading files into binary doesn't solve this. Maybe stating output directory for binaries in cmake?
-> now generates single workunit
-> check added
-> can you elaborate? I wasn't able to  reproduce this error.

**Comment by mathius** [comment]
Cannot really reproduce the last point, closing. Will be reopened, if necessary.
