### ISSUE TITLE
OneClick compilation bug

### ISSUE THREAD

**Issue by mathius** [crocs-muni/EACirc#112]
Cannot compile current OneClick HEAD (c8fb9).
4 errors when calling Utils::saveStringToFile

**Comment by LuboO** [comment]
What errors are you getting and what system are building on? In Visual Studio it compiles fine.

**Comment by mathius** [comment]
System spec: Fedora 21, 64bit, GCC 4.9.2, CMake 3.0.2

FAILED: /usr/bin/c++    -std=c++11 -Wall -Wextra -g -I../eacirc -I../projects -I../libs/tinyXML -MMD -MT oneclick/CMakeFiles/oneclick.dir/src/main.cpp.o -MF oneclick/CMakeFiles/oneclick.dir/src/main.cpp.o.d -o oneclick/CMakeFiles/oneclick.dir/src/main.cpp.o -c ../oneclick/src/main.cpp
In file included from ../oneclick/src/ResultProcessor.h:17:0,
                 from ../oneclick/src/main.cpp:5:
**../oneclick/src/PValuePostPr.h**: In member function '**virtual void PValuePostPr::calculateBatchResults()**':
../oneclick/src/PValuePostPr.h:83:70: **error: no matching function for call** to 'Utils::saveStringToFile(std::basic_string<char>, std::basic_ostringstream<char>::__string_type)'
   Utils::saveStringToFile(batchDirPath + PVALUES_FILE , pValues.str());
                                                                      ^
../oneclick/src/PValuePostPr.h:83:70: note: candidate is:
In file included from ../oneclick/src/OneclickConstants.h:13:0,
                 from ../oneclick/src/ResultProcessor.h:15,
                 from ../oneclick/src/main.cpp:5:
../oneclick/src/Utils.h:69:17: note: static void Utils::saveStringToFile(const string&, std::string&)
     static void saveStringToFile(const std::string & path , std::string & source) {
                 ^
../oneclick/src/Utils.h:69:17: note:   **no known conversion for argument 2 from 'std::basic_ostringstream<char>::__string_type {aka std::basic_string<char>}' to 'std::string& {aka std::basic_string<char>&}'**

**Comment by LuboO** [comment]
Fixed in commit 507df603c20c7070a7536f97b05534b4db50f77f , MSVC2013 is okay with const pointer being handled as non-const, gcc is not.
