### ISSUE TITLE
CUDA documentation

### ISSUE THREAD

**Issue by mathius** [crocs-muni/EACirc#114]
Write documentation concerning CUDA support on GitHub wiki.
(https://github.com/crocs-muni/EACirc/wiki/CUDA-support)
At least the following:
* tool support (compilers, versions)
* general principle (what is computed in CUDA, what is not)
* settings limitations (hat settings are incompatible with CUDA), run limitations (global memory usage preventing multiple instance of something?)
* recommended settings (for CUDA to actually speed things up -- effective test vector numbers, lengths, etc.)

**Comment by xtracko** [comment]
@mathius please read the first version of https://github.com/crocs-muni/EACirc/wiki/Cuda-support. I didn't written everything you said but I think it is sufficient. The details of my circuit implementation are in my thesis.

**Comment by mathius** [comment]
* Small reformatting and corrections done.
* Please add the used settings into the last paragraph (these options may change whenever -- I want to have the numbers the wiki speaks about written there).
