### ISSUE TITLE
BOINC default settings, OneClick settings

### ISSUE THREAD

**Issue by mathius** [crocs-muni/EACirc#118]
#### Description
The running of EACirc was changed slightly:
* The log is now autiomatic both to terminal and file (no "-log" needed).
* Graph files are no longer produced.
* Some other files are now also optional (score files, etc).
Necessary to do (both OneClick and BOINC settings):
* New default CLI arguments on BOINC (drop "-log").
* All files produced are optional (BOINC setting have their names [in brackets]). There will be some produced always, I'll let you know after I finish unifying verbosity levels.
* Edit: file with human readable test vectors was renamed (test_vectors_hr.txt -> test_vectors_debug.txt). Files produced in various verbosity levels summarized [in wiki](https://github.com/crocs-muni/EACirc/wiki/Running-EACirc).

#### Outputs
* New default settings in BOINC.
* New default settings in OneClick (revising file numbers may be necessary, consult assimilator).

**Comment by LuboO** [comment]
**New BOINC default settings:**
  * _Command line:_ -c FILE_0
  * _Output files:_ config.xml, eacirc.log, [scores.log], [fitness_progress.txt], [histograms.txt], [population_initial.xml], [population.xml], [state_initial.xml], [state.xml], [EAC_circuit.xml], [EAC_circuit.dot], [EAC_circuit.c], [EAC_circuit.txt]  

_Note for future changes:_ Default settings for work creation are intuitivelly stored in file: /home/boinc/labak/html/management/application/controllers/WorkController.php

**Oneclick changes:**
  * New default values added into upload_script_sample.pl
  * Revised file index constants in OneclickConstants.h - removed graph files constants, constants modified
  * Assimilator wasn't affected
