### ISSUE TITLE
CUDA validation

### ISSUE THREAD

**Issue by mathius** [crocs-muni/EACirc#120]
#### Description
After integration, run the same experiments on cuda and without cuda (use fixed seed). The outputs should be the same (with respect to rounding errors). Run multiple instances (at least 30) of each test, test all projects.

#### Outputs
Briefly describe in crcs wiki what settings were used for validation, if there were any errors (and why).

**Comment by xtracko** [comment]
Tested on Tangle, in 3 different settings. Results and settings are summarized on our wiki.
