### ISSUE TITLE
TEA experiments design

### ISSUE THREAD

**Issue by mathius** [crocs-muni/EACirc#121]
#### Description
Think of various TEA experiments (number of blocks, modes, ...). Make performance cost assumptions ("how long will it run"). Try to use CUDA, if possible.

#### Outputs
* Experiments description with performance estimates in crcs wiki.
* Discuss the experiments with Petr (force him to a call or chat).

**Comment by Bender250** [comment]
http://crcs.cz/wiki/doku.php?id=internal:research:eacirc:tea&#future_experiments
I will run experiments after CUDA implementation will be finished.
