### ISSUE TITLE
Get TestU01 working

### ISSUE THREAD

**Issue by mathius** [crocs-muni/EACirc#123]
#### Description
* Study the basics of TestU01, try it locally.
* Deploy a functioning installation on centaur in /home/eacirc (there's already an installation for NIST STS and Dieharder). Scripts for Dieharder and NIST STS located in src/utils might be helpful.

#### Outputs
* Crcs wiki page on test on centaur and short info on how to use them.

**Comment by LuboO** [comment]
TestU01 installed and working on Centaur. For details see https://github.com/crocs-muni/EACirc/wiki/TestU01-Usage

**Comment by mathius** [comment]
This is probably better written on internal wiki (crcs.cz), since it does not directly relate to EACirc.

**Comment by LuboO** [comment]
Good point, moved to http://crcs.cz/wiki/doku.php?id=internal:research:eacirc:statistical-testing:testu01-usage
