### ISSUE TITLE
Summarize statistical batteries

### ISSUE THREAD

**Issue by mathius** [crocs-muni/EACirc#124]
#### Description
* Try out available test batteries (at least NIST STS, Diehard, Dieharder, TestU01, maybe more).
* Find out the easiest way to run them ("getting the original Diehard is complicated, we will use its reimplementation in Dieharder").
* Get performance estimates (how long does it take to test the data in various batteries).

#### Outputs
* Choose one/two data sizes for data streams that will be used as a standard for testing.
* Briefly summarize all test suits in crcs wiki -- how many tests, reimplementations ("Dieharder has NIST STS as subset"), data size needed for tests, performance.

**Comment by LuboO** [comment]
Pages added at http://crcs.cz/wiki/doku.php?id=internal:research:eacirc:statistical-testing&#statistical_baterries_on_centaur

**Comment by mathius** [comment]
The crucial information about the individual tests is how much data do they require (this info is necessary to choose a right filesize for experiements).
Dieharder provides this information in test description, NIST STS can be configured (if I remember correctly), no idea about TestU01. Ideally create a table in the appropriate overview section.
Sidenote: Does TestU01 support running individual tests? Can this be used to determine how much data do the individual tests require (as opposed to the whole sets)?
Performance (time) estimates can wait for later, when we choose a file size.

**Comment by LuboO** [comment]
Page with stream lengths for individual tests in batteries added at http://crcs.cz/wiki/doku.php?id=internal:research:eacirc:statistical-testing:stream-lengths
