### ISSUE TITLE
EACirc not failing correctly when wrong cipher constant is set

### ISSUE THREAD

**Issue by LuboO** [crocs-muni/EACirc#130]
When I set illegal cipher constant in configuration file (eStream project), EACirc logs error (unknown cipher type), but continues to run until it fails at generator initialization. In debug it is unhandled expection, in release just "Application EACirc.exe stopped working."

**Config & log example:** https://drive.google.com/file/d/0Bw18bwKnQ9W_Q2JGS3VQaXBwWVk/view?usp=sharing
**System:** Windows 8
**Compiler:** Visual Studio 2013

**Comment by mathius** [comment]
Fixed by commit 1b47e8a1.
