### ISSUE TITLE
Caesar ciphers identification in Oneclick

### ISSUE THREAD

**Issue by mathius** [crocs-muni/EACirc#134]
How to properly identify ciphers in Oneclick?
There is no toString functions, descriptions are saved in the objects themselves.

**Comment by mathius** [comment]
Probably reimplement CAESAR to conform to the same structure as eStream and SHA3.

**Comment by mathius** [comment]
caesarToString function added. Old description system remains in place as well.

**Comment by LuboO** [comment]
Should I add CAESAR support into Oneclick? At the moment, if you try to generate jobs for CAESAR via Oneclick you'll get error "invalid project constant set at: EACIRC/MAIN/PROJECT".

**Comment by mathius** [comment]
What branch are sou checking? I have implemented CAESAR support in OneClick myself, should be working in both 'main' and 'oneclick' (commit ae98671)

**Comment by LuboO** [comment]
Didn't notice that, ignore my comment then :)

2015-07-20 13:07 GMT+02:00 Martin Ukrop <notifications@github.com>:
