### ISSUE TITLE
Oneclick tweaks

### ISSUE THREAD

**Issue by mathius** [crocs-muni/EACirc#139]
* Post-processing summary line (output to processed_results.txt) should also be added to batch log (not necessary to main log, but can be). The reason is that the file processed_results.txt gets rewritten later on and files produced within batches stay for archiving. Ideally prefix this line with something easily 'grep'-able
* Running Oneclick should first output some header (current server URL and such) for the user to know what kind of "name" and "pwd" is expected.
* Post-processor 1 should count the ratio of non-uniform instead of uniform.
* Display build commit at the beginning of log (same system as EACirc).

**Comment by LuboO** [comment]
Tweaks added in commit 17f5fe27cedcafed91ebea13ed064df2a72b73d1
