### ISSUE TITLE
Oneclick deploy to Centaur

### ISSUE THREAD

**Issue by mathius** [crocs-muni/EACirc#140]
Deploy Oneclick to Centaur to ease post-processing (processed results will be kept in the archive with computation files).
Ideally update source code at /home/eacirc/src and create an out-of-tree CMake build at /home/eacirc/oneclick
Centaur may not have the required minimal versions of compilers and CMake (consult with Mirek). Build target to avoid building EACirc may be necessary (consult with @xtracko ).

**Comment by LuboO** [comment]
Only executable could have been deployed. For details see https://github.com/crocs-muni/EACirc/wiki/Oneclick@Centaur
