### ISSUE TITLE
Logical/arithmetical shift?

### ISSUE THREAD

**Issue by mathius** [crocs-muni/EACirc#144]
How does C++'s shift function work? Does it keep sign bit?

**Comment by xtracko** [comment]
According to wikipedia: If you are shifting signed int, eg. `some_signed_int >> 5`, the arithmetical shift is performed (signed bit is carried). When you are shifting unsigned int, logical shift is performed.
Source (see note 3): https://en.wikipedia.org/wiki/Arithmetic_shift#cite_note-3
