### ISSUE TITLE
JVMSim without relational operators

### ISSUE THREAD

**Issue by mathius** [crocs-muni/EACirc#146]
Run tests without EQ, LT, GT … functions (they caused wrong results in non-JVM version).
Notice @mitko501 when Caesar experiments are finished.

**Comment by mathius** [comment]
Karel urgently needs to run some computations on CUDA, JVMSim is slightly postponed.

**Comment by Bender250** [comment]
I expect to finish my experiments in time of repaired bug https://github.com/crocs-muni/EACirc/issues/151 + 2 days. I hope in 16.9.

**Comment by Bender250** [comment]
Petr wants some more results, please wait a little longer (unspecified date).

**Comment by Bender250** [comment]
My part of computation for MKB2015 paper is finished. Now wait for @mathius approval.

**Comment by mathius** [comment]
Metacentrum tested, computations can start :-}.
