### ISSUE TITLE
Consult Cuda+JVMSim merge

### ISSUE THREAD

**Issue by mathius** [crocs-muni/EACirc#147]
Consult Cuda options with @xtracko and prepare JVMSim merge to new master.

**Comment by xtracko** [comment]
What do you wish to discuss? :)

**Comment by mathius** [comment]
Possibilities and opportunities. Basically, I need to arrange JVMSim merge with @mitko501 and since I cannot read the documentation for this part, I need to ask in person.
Relates to the email I've sent you some minutes ago.

**Comment by mathius** [comment]
Conclusion: JVMSim will be developed in Gate1, later (after @xtracko finishes gate2) will be merged into Gate2 (and Gate1 will be removed).
@mitko501: Please keep notes about necessary code modifications for integration later on.
