### ISSUE TITLE
JVMSim mutation callbacks

### ISSUE THREAD

**Issue by mukrop** [crocs-muni/eacirc#149]
Edit mutate callback function (move JVM mutation out of argument mutation cycle). Probably consult with Zdenek, Syso and Martin before code changes. (Maybe we will handle arguments in a more unified manner).

**Comment by mathius** [comment]
How did this end up, @mitko501 ?

**Comment by mitko501** [comment]
Well, I asked you about this, few months ago, and you said it has time. But I was thinking about this a lot, so we can get together and discuss it.

**Comment by mathius** [comment]
Ok, true.
Though, taking into account the big picture, it may not be necessary -- the back-end is now getting completely re-written by @xtracko. So all in all, the old back-end will become a sandbox for you. If your research proves interesting, it'll be moved to the new system after you defend your thesis.

**Comment by mathius** [comment]
For discussion at the next meeting, try to bring it up.
By the way, don't forget to read the minutes from today's EACirc meeting (will be on wiki in a few hours).

**Comment by mitko501** [comment]
Work on JVM Simulator is postponed for now, so I am closing this.
