### ISSUE TITLE
CUDA gives no error messages in case of trouble

### ISSUE THREAD

**Issue by mathius** [crocs-muni/EACirc#150]
When CUDA causes EACirc to fail in runtime (e.g. no CUDA device available), exception in cudaSafeCall() outputs nothing. This means the failure is rather cryptic (and the return value is probably messed up a bit, since BOINC did not understand the job failed).

**Comment by xtracko** [comment]
Had it fallen when you were running tests?

**Comment by mathius** [comment]
No, just running a normal computation (but had cuda-enabled build on cuda-unsupported machine). The above-mentioned commit solves the issue sufficiently.
