### ISSUE TITLE
Upgrade Travis build to Docker infrastructure

### ISSUE THREAD

**Issue by mathius** [crocs-muni/eacirc#153]
See [upgrade documentation from Travis](http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade). Sudo is not yet supported, but all necessary packages (including gcc-5.1) are whitelisted and can be installed using APT addon.

**Comment by xtracko** [comment]
Concept of a new Travis configuration with support of Travis docker technology can be found on https://github.com/xtracko/travis. Actualy we are waiting for any cmake-3.x ubuntu repository to be whitelisted. The actual whitelist of travis repositories can be found at https://github.com/travis-ci/apt-source-whitelist.

**Comment by xtracko** [comment]
Done in commit  43b0a97
