### ISSUE TITLE
Finalize measuremets of results

### ISSUE THREAD

**Issue by petrs** [crocs-muni/EACirc#155]

**Comment by Bender250** [comment]
For paper done, but I have a new ideas. I will run them after JVMSim computations #163.

**Comment by Bender250** [comment]
One more result (and very interesting one): http://crcs.cz/wiki/doku.php?id=research:eacirc:tea#summer_results
 PLAINTEXT_TYPE: first half is random, second is identical to the first but for one bitflip (6), but used 128 bits TV (so TV is 2 blocks of TEA output)
Rounds 	EACirc rejected [%] 
1 	100
2 	100
3 	100
4 	100
5 	4.5

**Comment by petrs** [comment]
this is ineed very interesting - what is current maximum size of input layer?

**Comment by Bender250** [comment]
NUM_LAYERS: 5
SIZE_LAYER: 8

Full xml: [teaTest.xml.txt](https://github.com/crocs-muni/EACirc/files/27575/teaTest.xml.txt)

But I think, that we have to discuss this result eye to eye - from my point of view, this says much more, than previous plaintext type 4 with same rounds count :).
