### ISSUE TITLE
Random to random results (5%)

### ISSUE THREAD

**Issue by petrs** [crocs-muni/EACirc#157]

**Comment by Bender250** [comment]
I will store results for some time here, until we will resolve, if we need page for validation tests.

Polynomials, using only mutation ([config.xml](https://github.com/crocs-muni/EACirc/files/29373/2015-11-06_EACcuda_eStream_a99r04_polRndMut.xml.txt)) resulted with 0.041289 (993 runs).

**Comment by Bender250** [comment]
Polynomials, using mutation and crossover (with 20 individuals) both on polynomials and terms ([config](https://github.com/crocs-muni/EACirc/files/32891/2015-11-07_EACcuda_eStream_a99r04_polRndAll.copy.xml.txt)) resulted with 0.043 (1000 runs).

For polynomials, we are done, but we still want to check, if using more individuals is OK. So I'll run one more experiment, this time with 10 000 runs.

**Comment by Bender250** [comment]
I expect, that results different from 5% were caused by polynomials count != 8*output_size. For this reason, I added another sanity check in configuration loading in commit https://github.com/crocs-muni/EACirc/commit/3f8c5c6eba467e8e7843f8c16ff80728c4fd6026.
