### ISSUE TITLE
Create configuration file for OneClick for fast testbed

### ISSUE THREAD

**Issue by petrs** [crocs-muni/EACirc#166]
- for fast testbed, upload cfg files into wiki

**Comment by xtracko** [comment]
angle (rounds 21-24), Dynamic SHA-1 (4-8), Dynamic SHA-2 (1-13), Decim (rounds 1-8), Boolean rng generator

**Comment by xtracko** [comment]
Shall I use 256 categories?

**Comment by mathius** [comment]
Make 2 versions:
* CUDA-enabled, 256 categories
* CUDA-disabled, 8 categories
