### ISSUE TITLE
Improve OneClick generation log

### ISSUE THREAD

**Issue by mathius** [crocs-muni/EACirc#179]
Include information on how many config files were generated (e.g. "123 generated config files" under the number of warnings and errors).

**Comment by LuboO** [comment]
Number of configs generated is announced at the end of config generation,
before creation of upload/download script. Is it necessary for it to be
after warning/error info? I would have to possibly rework logger for this.

2015-12-03 21:06 GMT+01:00 Martin Ukrop <notifications@github.com>:

**Comment by mathius** [comment]
I thought the information was somewhere but didn't see it.
Yes, it's there, no need to redo anything.
