### ISSUE TITLE
Caesar wont compile under vs2013

### ISSUE THREAD

**Issue by sysox** [crocs-muni/eacirc#185]
In these files:
projects/caesar/aead/omd/omdsha512k128n128tau128v1/omdsha512k128n128tau128v1_sha512.cpp
projects/caesar/aead/omd/omdsha512k256n256tau256v1/omdsha512k256n256tau256v1_sha512.cpp
projects/caesar/aead/omd/omdsha512k512n256tau256v1/omdsha512k512n256tau256v1_sha512.cpp
	
const uint64_t *W = in;

compiler can not deduce conversion between type of variable in and const uint64_t*.

**Comment by mathius** [comment]
Is not a MSVS2013 issue, compiles ok on my computer.
Can you provide som further diagnostic info?

**Comment by sysox** [comment]
1.
omdsha512k128n128tau128v1_sha512.cpp(142): error C2440: 'initializing' : 
cannot convert from 'const unsigned char []' to 'const 
Omdsha512k128n128tau128v1_raw::uint64_t *'
6>          Types pointed to are unrelated; conversion requires 
reinterpret_cast, C-style cast or function-style cast

2.
  omdsha512k256n256tau256v1_sha512.cpp(142): error C2440: 'initializing' 
: cannot convert from 'const unsigned char []' to 'const 
Omdsha512k256n256tau256v1_raw::uint64_t *'
6>          Types pointed to are unrelated; conversion requires 
reinterpret_cast, C-style cast or function-style cast

3.
  omdsha512k512n256tau256v1_sha512.cpp(142): error C2440: 'initializing' 
: cannot convert from 'const unsigned char []' to 'const 
Omdsha512k512n256tau256v1_raw::uint64_t *'
6>          Types pointed to are unrelated; conversion requires 
reinterpret_cast, C-style cast or function-style cast


Dňa 24. 2. 2016 o 18:10 Martin Ukrop napísal(a):

**Comment by mathius** [comment]
I could deduce that :-}.
What I wanted was environment info: Is it really MSVS2013? Most importantly, 32 or 64 bit compilation target? Compiling with OpenSSL? Debug or release?

**Comment by sysox** [comment]
MSVS2013,  32 bit,  Debug or/and release.



Dňa 28. 2. 2016 o 11:00 Martin Ukrop napísal(a):

**Comment by mathius** [comment]
Please try the compilation now (commit 0d7d0a33, current master head).

**Comment by mathius** [comment]
Tested yet, @sysox ?

**Comment by sysox** [comment]
Yes, It works now.
