### ISSUE TITLE
Move Oneclick to its own separate repo

### ISSUE THREAD

**Issue by xtracko** [crocs-muni/EACirc#186]
I think that Oneclick should be moved to it's own separate repository. The dependencies to EACirc could be nicely managed by [git submodules](http://www.diracprogram.org/doc/release-12/programmers/external_projects.html). Please @mathius and @LuboO discus.

**Comment by mathius** [comment]
Inspected the case, seem ok by me. Please do the split separately on GALib refactoring (i.e. make a branch, tune up the build system and git submodules, merge into master and possibly others, update wiki, email developers).

**Comment by xtracko** [comment]
On Monday Lubo said, that Oneclick will be soon deprecated (since RTT is alternative), so no need for a change.

**Comment by mathius** [comment]
Really? From my point ov view, the main point of Oneclick is generating EACirc config files and post-processing the computed results, none of which I expect to be done by RTT. Or am I mistaken?

**Comment by LuboO** [comment]
Ultimately, RTT should be able to do the same thing + run EACirc (at least
in my opinion)

2016-02-26 16:24 GMT+01:00 Martin Ukrop <notifications@github.com>:

**Comment by mathius** [comment]
I'm not sure incorporating EACirc into RTT in such a profound way is a good idea.
Nevertheless, I'm closing the issue for now since the future of Oneclick will need to be addressed in a broader manner.

**Comment by mathius** [comment]
OneClick will be kept, thus moving it into a separate repo (having EACirc as a git submodule).

**Comment by xtracko** [comment]
Migration of Oneclick was successfully completed. Oneclick is further accessible from [crocs-muni/oneclick](https://github.com/crocs-muni/oneclick).
All opened issues and all wiki pages regarding Oneclick were moved to a new repository. All invalidated wiki links were updated in the process.

**Comment by mathius** [comment]
Well, it's definitely not complete yet. I'll post issues into the new repository.
