### ISSUE TITLE
Incorrect implementation of AES-128 in the CAESAR project

### ISSUE THREAD

**Issue by matusn** [crocs-muni/EACirc#187]
Using a test vector from [NIST](http://csrc.nist.gov/publications/nistpubs/800-38a/sp800-38a.pdf) I have verified that the implemenation of [AES-128 encryption](https://github.com/crocs-muni/EACirc/blob/master/projects/caesar/aead/common/crypto_core_aes128encrypt.cpp) in the CAESAR project is faulty, what may have influenced the results of randomness testing for:

aes-cmcc (cmcc22v1)
aes-cpfb (aes128cpfbv1)
aes-gcm (aes128gcmv1)
paes (ppaev11)

AES-256 worked well for one used test vector.

Sources: [AES.zip](https://github.com/crocs-muni/EACirc/files/144517/AES.zip)

**Comment by matusn** [comment]
Decryption (crypto_core_aes128decrypt) seems to work well.

**Comment by mathius** [comment]
Good job! The results suggested such behaviour which most likely meant a bug somewhere.
Can you please verify the implementation at commit 18a53c0 (aesbug)?

PS: Finally I see that all the caution about changes and tracking system are useful, I found the original source and determined the difference and the cause in about 2 minutes :-}.

**Comment by matusn** [comment]
That fixed the problem, it seems that _numRounds_ was never initialized. Thanks!

**Comment by mathius** [comment]
Merged to master.
