### ISSUE TITLE
Gate function labeling

### ISSUE THREAD

**Issue by xtracko** [crocs-muni/eacirc#190]
In file `eacirc/circuit/gate/GateCommonFunctions.cpp` are wrongly labeled functions when writing to file.
```
    case FNC_SHIR:  return "ROTR";
    case FNC_ROTL:  return "CYCL";
    case FNC_ROTR:  return "CYCR";
    case FNC_EQ:    return "EQ";
```

**Comment by mathius** [comment]
Well, not wrongly but I caanot understand either why the naming convention
is different internally and exported.
Feel free to make it consistant again.
