### ISSUE TITLE
More random data for computation

### ISSUE THREAD

**Issue by mukrop** [crocs-muni/eacirc#191]
Download more quantum random data than 1.9GB. Distribute everywhere (Martin, Jirka, Petr, Matus, Syso, MefitasXX, Centaur, Metacentrum).

**Comment by xtracko** [comment]
Done

**Comment by Bender250** [comment]
Just documenting: done by removing dependency for QRNG. We use cryptographically strong PRNG (PCG32). For validation test, we would have to used data from QRNG service again.
