### ISSUE TITLE
Output raw stream data to a file

### ISSUE THREAD

**Issue by xtracko** [crocs-muni/eacirc#201]
This functionality should be available using CMD argument. The output data should be unprocessed (just as the cipher produced them).

From implementation point of view this functionality should be implemented in a different method than in eacirc::run (just create a new method eacirc::generate() or something different).

**Comment by petrs** [comment]
@xtracko Will this be solved by separate PRNG generator tool?

**Comment by Bender250** [comment]
Oh, I missed this, yes, this is solved by the separation of the generator tool. 

https://github.com/crocs-muni/eacirc/wiki/Generator

Even though it is just in `dev` branch, I think we can close it.
