### ISSUE TITLE
Create testing environment

### ISSUE THREAD

**Issue by xtracko** [crocs-muni/eacirc#215]
Create a environment for regression testing of eacirc's basic functionality, in order to catch silly bugs. Utilize Travis to automate the process of running the tests.

Decide whether to use [Googletest](https://github.com/google/googletest) or [Catch](https://github.com/philsquared/Catch) framework.

Don't forget to run the tests under valgrind in Travis.

**Comment by Bender250** [comment]
We really need tests. The https://github.com/crocs-muni/eacirc/issues/232 shows, we have multiple bugs in the code.

First (but not small) step should be again implement plaintext =?= decrypt(encrypt(plaintext)) for block and estream projects. The functions have decryption implemented.

Steps:

1. Decide for test framework. I and @mitko501 have experience with GoogleCheck, so I would prefer it.
2. Mockup the streams and state some simple tests (like counter returns 0x01, then 0x02...).
3. Implement test classes of projects, that take all the ciphers and try decrypt(encrypt(plaintext) == plaintex.
4. (nice to have) Try to get official test vectors at least for usable testbed (especially for SHA-3, as it is not tested by 3.) and check them.

**Comment by Bender250** [comment]
How is this going? Can some progress be committed?

**Comment by mitko501** [comment]
I am working on it, I pushed some changes, I needed to refactor streams.h and streams.cc [26b5a2](https://github.com/crocs-muni/eacirc-streams/commit/26b5a2f071e28f4c913c1abaf9f80ad2eb5708af)
