### ISSUE TITLE
Add PRNGs from TestU01

### ISSUE THREAD

**Issue by ph4r05** [crocs-muni/eacirc#217]
There are few interesting PRNGs (over 40) implemented in the [TestU01 test suite](http://www.iro.umontreal.ca/~simardr/testu01/guideshorttestu01.pdf). It can be also found on [GitHub](https://github.com/apex-hughin/TestU01/tree/master/testu01).

They can be used for testing or benchmarking of the baseline or directly for experiments. Moreover parameters can be tweaked so be obtain stronger or weaker PRNGs. 

For example there are:

 * LSFR generators
 * Linear congruential generators, also with instantiations used in the wild (e.g., C stdlib, MS Excel, Maple, VisualBasic, VAX, Fortran, ...), 
 * Multiplicative congruential generators
 * Add-with-carry generators
 * Generalized feedback shift register (GFSR)
 * Twisted GFSR
 * Tempered TGFSR (Mersenne Twister family)
 * Inversive generators
 * Cubic congruential generators
 * Xorshift
 * And many others proposed in an academic literature (e.g., by Knuth, Marsaglia, L’Ecuyer, Brent, ...)

Some of they are little bit tricky to seed - one has to pick some parameters while the parameters domains differ and some are better than others (e.g., primes vs. smooth numbers). I personally used GFSR, TGFSR, TTGFSR generators which are easy to seed and it worked well.

We may also add [TinyMersenneTwister](http://www.math.sci.hiroshima-u.ac.jp/~m-mat/MT/TINYMT/) with only 127 bit state - recommended for small embedded devices.

**Comment by Bender250** [comment]
I will show you how to create new stream, and can you implement this to `dev`?
