### ISSUE TITLE
Update wiki

### ISSUE THREAD

**Issue by Bender250** [crocs-muni/eacirc#218]
XML -> JSON...

**Comment by Bender250** [comment]
>60 % done.

Remains:
* https://github.com/crocs-muni/eacirc/wiki/Running-EACirc - @mitko501 
* https://github.com/crocs-muni/eacirc/wiki/Circuit-back-end - @xtracko 
* https://github.com/crocs-muni/eacirc/wiki/Third-party-libraries - @mitko501 
* https://github.com/crocs-muni/eacirc/wiki/Program-files-structure - @mitko501 
* SHA3, eStream - me
* homepage - me
* https://github.com/crocs-muni/eacirc/wiki/Gate-circuits - @xtracko 

Revise:
* https://github.com/crocs-muni/eacirc/wiki/Building-EACirc - @xtracko 
* https://github.com/crocs-muni/eacirc/wiki/Recommencing-computation - @mitko501 
* https://github.com/crocs-muni/eacirc/wiki/Configuration-file-(JSON) - me

Check all remaining files and delete the obsolete ones (:D many).

**Comment by mitko501** [comment]
I updated the wiki, can you please check my changes? 

- https://github.com/crocs-muni/eacirc/wiki/Running-EACirc
- https://github.com/crocs-muni/eacirc/wiki/Program-files-structure
- https://github.com/crocs-muni/eacirc/wiki/Third-party-libraries

**Comment by Bender250** [comment]
Thanks, I did small change in pvals.txt description, check if you agree :).

**Comment by Bender250** [comment]
Added [Generator tool short description](https://github.com/crocs-muni/eacirc/wiki/Generator).

Other parts have delays...

**Comment by Bender250** [comment]
I have done my part and I did little bit of @xtracko's https://github.com/crocs-muni/eacirc/wiki/Circuit-back-end.

Can someone check the streams?

**Comment by Bender250** [comment]
>85% done

Missing only:

- [ ] https://github.com/crocs-muni/eacirc/wiki/Circuit-back-end
- [ ] Add core (our library) documentation
