### ISSUE TITLE
More eSTREAM function can be round-reduced

### ISSUE THREAD

**Issue by Bender250** [crocs-muni/eacirc#232]
Most of the eSTREAM functions in EACirc are not round reduced. But many can be.

Example (but further analysis will be done):

[SOSEMANUK](http://www.ecrypt.eu.org/stream/p2ciphers/sosemanuk/sosemanuk_p2.pdf) was not reduced, but the function has 25 rounds (nice feistel structure in the paper linked). The code is full of macros, so it is uneasy. But we need to state this fact at least in the [wiki](https://github.com/crocs-muni/eacirc/wiki/eStream-ciphers)!

Ultimate, but achievable goal: round reduce all the finalists and at least try to understand, what other functions have rounds.

**Comment by Bender250** [comment]
OK, SOSEMANUK IS somehow round reduced, but it looks [inverted (the less rounds is set, the more are executed)](https://github.com/crocs-muni/eacirc/blob/master/streams/estream/ciphers/sosemanuk/sosemanuk.cpp#L633). And the variable _rounds is unset (default to -1).

I have to inspect the original code...

**Comment by Bender250** [comment]
Noooo! [I have to stop finding other bugs](https://i.imgur.com/t0XHtgJ.gif).

(eSTREAM is wrongly initialized, when the TV is longer than block length. It is zero padded.)

**Comment by Bender250** [comment]
Fourth for today? All estream ciphers have same block size (estream_cipher::block_size constexpr)?

**Comment by Bender250** [comment]
@046c116 Fixes the fixed block length and therefore eSTREAM::TEA behaves like in EACirc 3. Which means, we can distinguish 4 rounds eSTREAM::TEA, while only 3 rounds block::TEA. What? :(

**Comment by Bender250** [comment]
SOSEMANUK round reduced cf2dcfa and ed39da6.

**Comment by xtracko** [comment]
Why we still have 2 versions of TEA (eSTREAM and block)? (even copy pasted?)

eSTREAM works as a stream - it continuously produces small chunks of data of constant size. TEA should not be there, it is a block cypher! Am I right or wrong?

**Comment by Bender250** [comment]
Yes, we should have removed it, it is my mistake, but it helps to debug current situation. When I will solve this, I will remove eSTREAM::TEA.

**Comment by Bender250** [comment]
Checked and fixed in:

https://github.com/crocs-muni/eacirc-streams/commit/cd1edc0d2cd144afa7878b13edb8b34b7fc84bdf
https://github.com/crocs-muni/eacirc-streams/commit/6b68124d7fc545ae8949020a42cc8e345388cc61
https://github.com/crocs-muni/eacirc-streams/commit/e62b2fdf579730952dbe2bcffa572fa0a18a99cd

The changes described in the [wiki](https://github.com/crocs-muni/eacirc/wiki/eStream-ciphers), which was polished and updated for upcomming publication of the generator.
