### ISSUE TITLE
Pruner implementation

### ISSUE THREAD

**Issue by mukrop** [crocs-muni/eacirc#78]

**Comment by mathius** [comment]
Partly implemented by @Bender250. Not documented on wiki yet.
Closing for now, since the back-end is going to be rapidly re-written (and we'll see whether the prunner in this form is still applicable).

**Comment by mathius** [comment]
Make pruner actually modifying the circuit, enhance the used techniques combining Karel's and Petr's approach (deterministic connection analysis, evaluating circuits on much data and looking for changes).

**Comment by Bender250** [comment]
Pruner is currently waiting for Jirka's implementation of new circuits. Then I will implement pruning directly on circuits and later dump circuit to graphviz as well.

**Comment by Bender250** [comment]
![17236968_1468297176536418_379157251_o](https://cloud.githubusercontent.com/assets/3519476/23836105/38c0823a-0773-11e7-86ca-eca6a8719e5a.png)

We have again graphviz visualization! :)

**Comment by LuboO** [comment]
This must be the one time when visualisation of a problem does not actually
help you.

**Comment by Bender250** [comment]
Of course, pruning is the next step. And this is by the way a random individual, so probably with low fitness.
